# Generated by Django 3.2.6 on 2021-09-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('temperature', models.CharField(max_length=100)),
                ('humidity', models.CharField(max_length=100)),
                ('wind_speed', models.CharField(max_length=100)),
                ('date', models.DateField(max_length=100)),
                ('time', models.CharField(max_length=100)),
            ],
        ),
    ]
