# Generated by Django 3.2.6 on 2021-09-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
